# Generated by Django 5.2 on 2026-02-14 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_user_options_alter_systemlog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('base_price', models.FloatField()),
                ('demand_supply_factor', models.FloatField()),
                ('renewable_bonus', models.FloatField()),
                ('congestion_factor', models.FloatField()),
                ('time_of_use_multiplier', models.FloatField()),
                ('final_price', models.FloatField()),
                ('grid_zone', models.CharField(choices=[('ZONE_A', 'Zone A'), ('ZONE_B', 'Zone B'), ('ZONE_C', 'Zone C')], max_length=20)),
            ],
            options={
                'db_table': 'dynamic_pricing',
            },
        ),
        migrations.CreateModel(
            name='EnergyMeasurement',
            fields=[
                ('measurement_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('energy_generated_kwh', models.FloatField(default=0)),
                ('energy_consumed_kwh', models.FloatField(default=0)),
                ('battery_charge_level', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'energy_measurements',
            },
        ),
        migrations.CreateModel(
            name='EnergyTokenTransaction',
            fields=[
                ('token_tx_id', models.AutoField(primary_key=True, serialize=False)),
                ('energy_amount_kwh', models.FloatField()),
                ('tokens_minted', models.FloatField(default=0)),
                ('tokens_burned', models.FloatField(default=0)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'energy_tokens',
            },
        ),
        migrations.CreateModel(
            name='MonthlyBilling',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('grid_energy_used_kwh', models.FloatField()),
                ('base_bill_amount', models.FloatField()),
                ('tokens_redeemed', models.FloatField(default=0)),
                ('token_value_rs', models.FloatField(default=0)),
                ('final_bill_amount', models.FloatField()),
                ('payment_status', models.CharField(choices=[('PENDING', 'pending'), ('PAID', 'paid'), ('FAILED', 'failed')], default='PENDING', max_length=15)),
            ],
            options={
                'db_table': 'monthly_billing',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('BUY', 'Buy Energy'), ('SELL', 'Sell Energy')], max_length=10)),
                ('energy_amount_kwh', models.FloatField()),
                ('price_per_kwh', models.FloatField()),
                ('time_slot_start', models.DateTimeField()),
                ('time_slot_end', models.DateTimeField()),
                ('order_status', models.CharField(choices=[('OPEN', 'Open'), ('MATCHED', 'Matched'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='TradeMatch',
            fields=[
                ('trade_id', models.AutoField(primary_key=True, serialize=False)),
                ('energy_amount', models.FloatField()),
                ('trade_price', models.FloatField()),
                ('blockchain_settlement_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('settlement_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trade_matches',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_address', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('token_balance', models.FloatField(default=0)),
                ('last_synced_block', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.DeleteModel(
            name='AdminSetting',
        ),
        migrations.RemoveField(
            model_name='smartmeter',
            name='user',
        ),
        migrations.RemoveField(
            model_name='systemlog',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='energymeasurement',
            name='meter',
            field=models.ForeignKey(db_column='meter_id', on_delete=django.db.models.deletion.CASCADE, related_name='energy_measurements', to='dashboard.user'),
        ),
        migrations.AddField(
            model_name='energytokentransaction',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='token_transactions', to='dashboard.user'),
        ),
        migrations.AddField(
            model_name='monthlybilling',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='dashboard.user'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dashboard.user'),
        ),
        migrations.AddField(
            model_name='tradematch',
            name='buy_order',
            field=models.ForeignKey(db_column='buy_order_id', on_delete=django.db.models.deletion.CASCADE, related_name='buy_trades', to='dashboard.order'),
        ),
        migrations.AddField(
            model_name='tradematch',
            name='buyer',
            field=models.ForeignKey(db_column='buyer_id', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='dashboard.user'),
        ),
        migrations.AddField(
            model_name='tradematch',
            name='sell_order',
            field=models.ForeignKey(db_column='sell_order_id', on_delete=django.db.models.deletion.CASCADE, related_name='sell_trades', to='dashboard.order'),
        ),
        migrations.AddField(
            model_name='tradematch',
            name='seller',
            field=models.ForeignKey(db_column='seller_id', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='dashboard.user'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='dashboard.user'),
        ),
        migrations.DeleteModel(
            name='MeterReading',
        ),
        migrations.DeleteModel(
            name='SmartMeter',
        ),
        migrations.DeleteModel(
            name='Systemlog',
        ),
    ]
